### ISSUE TITLE
 Wrong pre-build application of MacOS

### ISSUE THREAD

**Issue by GongTen** [wearable-motion-capture/.github#2]
Hello!

I was trying to download the pre-build application of MacOS. But after I download the file named "mac_build_v3.zip" and unzip it, I got the folder named "linux_build" rather than "mac_build".

I was wondering if it is a mistake of the download link and hoping to get a "mac_build" version

Thanks!

**Comment by faweigend** [comment]
Thanks for letting me know and I apologize for the late reply and the mistake! I will re-upload a new pre-build version soon.

**Comment by faweigend** [comment]
I updated the Mac app and the link. You can find the newest version [here](https://drive.google.com/drive/folders/18LDbT_E33oyWSd0J2E86wi2IfsF00x9S?usp=sharing). Let me know if there are any issues!
